service: dio-serverless-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                  # - dynamodb:PutItem
                  # - dynamodb:UpdateItem
                  # - dynamodb:GetItem
                  # - dynamodb:Scan
              Resources:
                - arn:aws:dynamodb:us-east-1:229671155013:table/ItemTableNew

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    events: 
      - http:
          path: /item
          method: post

resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
            
